import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/features";
import { BackgroundBeamsWithCollision } from "@/ui/aceternity";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full h-fit min-h-screen">
        <Providers>
          <BackgroundBeamsWithCollision>
            {children}
          </BackgroundBeamsWithCollision>
        </Providers>
      </body>
    </html>
  );
}
